name: GARM test workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  garm:
    runs-on: [ ubuntu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          sleep 60
